### ISSUE TITLE
Issue with project file

### ISSUE THREAD

**Issue by doan** [davidgassner/KotlinEssentialTraining#3]
Hi David,

I am following this tutorial and downloaded the exercise files. I am at 1.4 and your on-screen instructions show that I should be able to run the project choosing MainKt but on mine, the dialog only shows "0. Edit Configuration". I tried building the module but it's not working. Any suggestions?

<img width="669" alt="screen shot 2018-07-25 at 1 15 33 pm" src="https://user-images.githubusercontent.com/152672/43224982-d4e9db02-900c-11e8-8ade-6b56be9a77db.png">

**Comment by davidgassner** [comment]
It looks like Kotlin isn't configured correctly upon checking out the project. Try these steps:
* In the Project window, right-click on the src directory
* Create a new Kotlin file (the name can be anything)
* Follow the prompts to set the project SDK
* Switch back to viewing main.kt.
* Try the Run command again. You should now see MainKt appear in the Run list. 
* The extra file you created can be deleted.
